### ISSUE TITLE
Idiot hardened release checklist

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#714]
## Changelog

- [ ] Covers most new features and bug fixes
- [ ] Has correct date
- [ ] Is committed

## Tags

- [ ] `scripts/version.js bump ` + {2,1,0} in descending likelihood
- [ ] `git push --tags && git push`

## Build / sign

- [ ] SSH into buildbot
- [ ] Check beta build is built
- [ ] Check beta works
- [ ] `scripts/sign stable` and wait for it to complete
- [ ] Download source from https://tridactyl.cmcaine.co.uk/betas/
- [ ] Upload source to https://addons.mozilla.org/en-US/developers/addon/tridactyl-vim/versions

## Aftermath
- [ ] Check stable version works
- [ ] Check if the number of people with Tridactyl disabled ticks up https://addons.mozilla.org/en-US/firefox/addon/tridactyl-vim/statistics/usage/status/?last=7
