### ISSUE TITLE
Roadmap / todolist / missing features

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#90]
In no particular order, and non-exhaustive:

- [ ] extoptions (optionsUrl from https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/management/ExtensionInfo)
- [ ] extra hint modes (rapid, yank, save content, etc.)
- [ ] completions: web history, tabs, search suggestions, command history
- [ ] web history (fuzzy, frecency)
- [ ] user preferences / config: search engines, default tab page
- [ ] parser: allow modifiers, `noremap j 10j`
- [ ] native messenger
- [ ] embedded vim / edit text area in vim / "codemirror vim here"
- [ ] autocmds
- [ ] status line
- [ ] command history search (fish-style up/down keys, maybe?)

Eventually, we'll use this issue for identifying good places for new contributors to start.

**Comment by hppavilion1** [comment]
I've submitted a PR for a basic config page; next thing to do is allow command-line-only config.

**Comment by Koushien** [comment]
User-configurable blacklist, as seems to be requested by reviews on AMO.
